using System.Reflection;
using HarmonyLib;

namespace HistoricalCareer
{
    [HarmonyPatch(typeof(CareerManager))]
    static class CareerPatcher
    {
        [HarmonyPatch(nameof(CareerManager.SetSeasonInProgress))]
        [HarmonyPostfix]
        static void SetSeasonInProgress_Postfix(CareerManager __instance, Season TheSeason)
        {
            Main.Try("SetSeasonInProgress Postfix", () =>
            {
                if (TheSeason != null)
                {
                    // let's just assume the season is OK since it's generated by the mod
                    TheSeason.ResetValuesForStartingNewSeason();
                    TheSeason.Status = Season.STATUS.IN_PROGRESS;

                    // checks in the og code are super weird
                    if (TheSeason != null && TheSeason.SelectedCar != null && TheSeason.SelectedCar.performancePartsCondition != null)
                        TheSeason.SelectedCar.performancePartsCondition.ClampValues();

                    TheSeason.ResetStageInfo();
                    TheSeason.ResetRoadSurface();
                    TheSeason.RemoveDLCCar();

                    Main.SetField(__instance, "CurrentSeasonInProcess", BindingFlags.Instance, TheSeason);
                    SaveManager.SetSeasonStatus(TheSeason, Season.STATUS.IN_PROGRESS);
                    Main.Log("Set season in progress");
                }
            });
        }

        [HarmonyPatch("CheckIfContainsSeasonAndUnlockNextOnes")]
        [HarmonyPostfix]
        static void CheckIfContainsSeasonAndUnlockNextOnes_Postfix(Season season)
        {
            Main.Try("CheckIfContainsSeasonAndUnlockNextOnes Postfix", () =>
            {
                if (season != null)
                {
                    RallyManager.UnlockNextSeason(season);
                    Main.Log("Unlock next season " + RallyManager.GetSeasonCode(season));
                }
            });
        }

        [HarmonyPatch("UnlockSeasonClasses")]
        [HarmonyPostfix]
        static void UnlockSeasonClasses_Postfix()
        {
            // TODO : Do I need to do something there ?
            Main.Log("Unlock next group");
        }

        [HarmonyPatch(nameof(CareerManager.ResetAllInProgressSeasons))]
        [HarmonyPostfix]
        static void ResetAllInProgressSeasons_Postfix()
        {
            // TODO : Do I need this ?
            Main.Log("Reset all in progress seasons");
        }
    }
}
