using System.Collections.Generic;
using System.Reflection;
using HarmonyLib;

namespace HistoricalCareer
{
    [HarmonyPatch(typeof(CareerManager))]
    static class CareerPatcher
    {
        const string CURRENT_SEASON_FLAG = "CurrentSeasonInProcess";

        [HarmonyPatch(nameof(CareerManager.SetSeasonInProgress))]
        [HarmonyPrefix]
        static bool StartCustomSeason(CareerManager __instance, Season TheSeason)
        {
            if (Main.enabled && TheSeason != null)
            {
                Main.Try(nameof(StartCustomSeason), () =>
                {
                    if (TheSeason != null)
                    {
                        // let's just assume the season is OK since it's generated by the mod
                        TheSeason.ResetValuesForStartingNewSeason();
                        TheSeason.Status = Season.STATUS.IN_PROGRESS;

                        // checks in the og code are super weird
                        if (TheSeason != null && TheSeason.SelectedCar != null && TheSeason.SelectedCar.performancePartsCondition != null)
                            TheSeason.SelectedCar.performancePartsCondition.ClampValues();

                        TheSeason.ResetStageInfo();
                        TheSeason.ResetRoadSurface();

                        // if I don't do this it crashes
                        Main.SetField(__instance, CURRENT_SEASON_FLAG, BindingFlags.Instance, TheSeason);
                        Main.SetField(GameModeManager.CareerManager, CURRENT_SEASON_FLAG, BindingFlags.Instance, TheSeason);
                        SaveManager.SaveSeasonData(TheSeason);

                        Main.Log("Starting season : " + RallyManager.GetSeasonCode(TheSeason));
                    }
                });

                return false;
            }

            return true;
        }

        [HarmonyPatch("CheckIfContainsSeasonAndUnlockNextOnes")]
        [HarmonyPrefix]
        static bool CheckSeasonUnlock(Season season)
        {
            if (Main.enabled && season != null)
            {
                RallyManager.UnlockNextSeason(season);
                return false;
            }

            return true;
        }

        // Prevent save corruption crashes
        [HarmonyPatch(nameof(CareerManager.GetCurrentSeasonBoot))]
        [HarmonyPrefix]
        static void SanitizeOGSeasons(CareerManager __instance)
        {
            if (!Main.enabled)
                return;

            Main.Try(nameof(SanitizeOGSeasons), () =>
            {
                foreach (List<Season> seasons in __instance.AllSeasons)
                {
                    foreach (Season season in seasons)
                    {
                        if (season == null)
                            Main.Log("Null season detected");
                        else if (season.Status == Season.STATUS.IN_PROGRESS)
                            season.Status = Season.STATUS.UNLOCKED;
                    }
                }
            });
        }

        [HarmonyPatch(nameof(CareerManager.GetCurrentSeasonBoot))]
        [HarmonyPrefix]
        static bool GetCustomBootSeason(ref Season __result)
        {
            if (!Main.enabled)
                return true;

            RallySettings settings = RallyManager.GetRallyInProgress();
            __result = settings?.season;

            Main.Log("Has boot season : " + (__result != null));
            return false;
        }

        [HarmonyPatch(nameof(CareerManager.IsASeasonInProgress))]
        [HarmonyPrefix]
        static bool HasCurrentSeason(ref bool __result)
        {
            if (!Main.enabled)
                return true;

            __result = RallyManager.GetRallyInProgress() != null;
            return false;
        }

        [HarmonyPatch(nameof(CareerManager.ResetAllInProgressSeasons))]
        [HarmonyPostfix]
        static void ResetAllInProgressSeasons_Postfix()
        {
            if (Main.enabled)
                RallyManager.ResetRallyInProgress();
        }
    }
}
