using System.Collections.Generic;
using System.Reflection;
using HarmonyLib;

namespace HistoricalCareer
{
    [HarmonyPatch(typeof(CareerManager))]
    static class CareerPatcher
    {
        [HarmonyPatch(nameof(CareerManager.SetSeasonInProgress))]
        [HarmonyPostfix]
        static void StartCustomSeason(CareerManager __instance, Season TheSeason)
        {
            Main.Try(nameof(StartCustomSeason), () =>
            {
                if (TheSeason != null)
                {
                    // let's just assume the season is OK since it's generated by the mod
                    TheSeason.ResetValuesForStartingNewSeason();
                    TheSeason.Status = Season.STATUS.IN_PROGRESS;

                    // checks in the og code are super weird
                    if (TheSeason != null && TheSeason.SelectedCar != null && TheSeason.SelectedCar.performancePartsCondition != null)
                        TheSeason.SelectedCar.performancePartsCondition.ClampValues();

                    TheSeason.ResetStageInfo();
                    TheSeason.ResetRoadSurface();

                    Main.SetField(__instance, "CurrentSeasonInProcess", BindingFlags.Instance, TheSeason);
                    SaveManager.SaveSeasonData(TheSeason);

                    Main.Log("Starting season : " + RallyManager.GetSeasonCode(TheSeason));
                }
            });
        }

        [HarmonyPatch("CheckIfContainsSeasonAndUnlockNextOnes")]
        [HarmonyPrefix]
        static bool CheckSeasonUnlock(Season season)
        {
            if (Main.enabled && season != null)
            {
                RallyManager.UnlockNextSeason(season);
                return false;
            }

            return true;
        }

        // Prevent save corruption crashes
        [HarmonyPatch(nameof(CareerManager.GetCurrentSeasonBoot))]
        [HarmonyPrefix]
        static void SanitizeOGSeasons(CareerManager __instance)
        {
            Main.Try(nameof(SanitizeOGSeasons), () =>
            {
                foreach (List<Season> seasons in __instance.AllSeasons)
                {
                    foreach (Season season in seasons)
                    {
                        if (season == null)
                            Main.Log("Null season detected");
                        else if (season.Status == Season.STATUS.IN_PROGRESS)
                            season.Status = Season.STATUS.UNLOCKED;
                    }
                }
            });
        }

        [HarmonyPatch(nameof(CareerManager.GetCurrentSeasonBoot))]
        [HarmonyPostfix]
        static void GetCustomBootSeason(ref Season __result)
        {
            __result = RallyManager.GetSeasonInProgress();
        }

        [HarmonyPatch(nameof(CareerManager.ResetAllInProgressSeasons))]
        [HarmonyPostfix]
        static void ResetAllInProgressSeasons_Postfix()
        {
            // TODO : Do I need this ?
            Main.Log("Reset all in progress seasons");
        }
    }
}
